name: app_conteo
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.2.5    # Para seleccionar archivos desde el dispositivo
  excel: ^2.0.7          # Para leer archivos Excel
  sqflite: ^2.2.8        # Para manejar SQLite
  path: ^1.8.3 
  mobile_scanner: ^6.0.2
  awesome_dialog: ^3.0.0
  path_provider: ^2.0.11
  intl: ^0.17.0
  


  cupertino_icons: ^1.0.6
  csv: ^6.0.0
  flexible_scrollbar: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/
  
flutter_launcher_icons:
  android: true
  ios: true 
  image_path: "assets/icon/logo_conteo.png"




  
  